# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "343e64a376970b9b21eb2d848b7b42ee"
name = "Planet Beauty AI Chat"
handle = "planet-beauty-ai-chat"
application_url = "https://lightbox-signs-pa-minnesota.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lightbox-signs-pa-minnesota.trycloudflare.com/auth/callback",
  "https://lightbox-signs-pa-minnesota.trycloudflare.com/auth/shopify/callback",
  "https://lightbox-signs-pa-minnesota.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
